/**
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin2.configurator;

import itu.xtext.landin2.configurator.ExcoStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ExcoStandaloneSetup extends ExcoStandaloneSetupGenerated {
  public static void doSetup() {
    ExcoStandaloneSetup _excoStandaloneSetup = new ExcoStandaloneSetup();
    _excoStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
