/**
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin2.configurator;

import itu.xtext.landin2.configurator.AbstractExcoRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ExcoRuntimeModule extends AbstractExcoRuntimeModule {
}
