/*
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin2.configurator


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ExcoStandaloneSetup extends ExcoStandaloneSetupGenerated {

	def static void doSetup() {
		new ExcoStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
