/*
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin2.configurator


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ExcoRuntimeModule extends AbstractExcoRuntimeModule {
}
