/*
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin2.configurator.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ExcoAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("itu/xtext/landin2/configurator/parser/antlr/internal/InternalExco.tokens");
	}
}
