/*
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin2.configurator.parser.antlr;

import com.google.inject.Inject;
import itu.xtext.landin2.configurator.parser.antlr.internal.InternalExcoParser;
import itu.xtext.landin2.configurator.services.ExcoGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ExcoParser extends AbstractAntlrParser {

	@Inject
	private ExcoGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalExcoParser createParser(XtextTokenStream stream) {
		return new InternalExcoParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ExcoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ExcoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
