/**
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin2.configurator.validation;

import itu.xtext.landin2.configurator.validation.AbstractExcoValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ExcoValidator extends AbstractExcoValidator {
}
