/**
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin2.configurator.scoping;

import itu.xtext.landin2.configurator.scoping.AbstractExcoScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ExcoScopeProvider extends AbstractExcoScopeProvider {
}
