/**
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin2.configurator.ui;

import itu.xtext.landin2.configurator.ui.AbstractExcoUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ExcoUiModule extends AbstractExcoUiModule {
  public ExcoUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
