/**
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin2.configurator.ui.contentassist;

import itu.xtext.landin2.configurator.ui.contentassist.AbstractExcoProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ExcoProposalProvider extends AbstractExcoProposalProvider {
}
