/**
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin2.configurator.exco;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Configurator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link itu.xtext.landin2.configurator.exco.Configurator#getTitle <em>Title</em>}</li>
 *   <li>{@link itu.xtext.landin2.configurator.exco.Configurator#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see itu.xtext.landin2.configurator.exco.ExcoPackage#getConfigurator()
 * @model
 * @generated
 */
public interface Configurator extends EObject
{
  /**
   * Returns the value of the '<em><b>Title</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Title</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' containment reference.
   * @see #setTitle(Title)
   * @see itu.xtext.landin2.configurator.exco.ExcoPackage#getConfigurator_Title()
   * @model containment="true"
   * @generated
   */
  Title getTitle();

  /**
   * Sets the value of the '{@link itu.xtext.landin2.configurator.exco.Configurator#getTitle <em>Title</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' containment reference.
   * @see #getTitle()
   * @generated
   */
  void setTitle(Title value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference list.
   * The list contents are of type {@link itu.xtext.landin2.configurator.exco.Expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference list.
   * @see itu.xtext.landin2.configurator.exco.ExcoPackage#getConfigurator_Expression()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getExpression();

} // Configurator
