/**
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin2.configurator.exco;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see itu.xtext.landin2.configurator.exco.ExcoFactory
 * @model kind="package"
 * @generated
 */
public interface ExcoPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "exco";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.itu/landin2/configurator/Exco";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "exco";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ExcoPackage eINSTANCE = itu.xtext.landin2.configurator.exco.impl.ExcoPackageImpl.init();

  /**
   * The meta object id for the '{@link itu.xtext.landin2.configurator.exco.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see itu.xtext.landin2.configurator.exco.impl.ModelImpl
   * @see itu.xtext.landin2.configurator.exco.impl.ExcoPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Configurator</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CONFIGURATOR = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link itu.xtext.landin2.configurator.exco.impl.ConfiguratorImpl <em>Configurator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see itu.xtext.landin2.configurator.exco.impl.ConfiguratorImpl
   * @see itu.xtext.landin2.configurator.exco.impl.ExcoPackageImpl#getConfigurator()
   * @generated
   */
  int CONFIGURATOR = 1;

  /**
   * The feature id for the '<em><b>Title</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATOR__TITLE = 0;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATOR__EXPRESSION = 1;

  /**
   * The number of structural features of the '<em>Configurator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATOR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link itu.xtext.landin2.configurator.exco.impl.TitleImpl <em>Title</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see itu.xtext.landin2.configurator.exco.impl.TitleImpl
   * @see itu.xtext.landin2.configurator.exco.impl.ExcoPackageImpl#getTitle()
   * @generated
   */
  int TITLE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Title</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link itu.xtext.landin2.configurator.exco.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see itu.xtext.landin2.configurator.exco.impl.ExpressionImpl
   * @see itu.xtext.landin2.configurator.exco.impl.ExcoPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 3;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__LEFT = 0;

  /**
   * The feature id for the '<em><b>Operation</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__OPERATION = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__RIGHT = 2;

  /**
   * The feature id for the '<em><b>Paranthesis</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__PARANTHESIS = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__NAME = 4;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link itu.xtext.landin2.configurator.exco.impl.FreeTextImpl <em>Free Text</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see itu.xtext.landin2.configurator.exco.impl.FreeTextImpl
   * @see itu.xtext.landin2.configurator.exco.impl.ExcoPackageImpl#getFreeText()
   * @generated
   */
  int FREE_TEXT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FREE_TEXT__NAME = 0;

  /**
   * The number of structural features of the '<em>Free Text</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FREE_TEXT_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link itu.xtext.landin2.configurator.exco.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see itu.xtext.landin2.configurator.exco.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link itu.xtext.landin2.configurator.exco.Model#getConfigurator <em>Configurator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Configurator</em>'.
   * @see itu.xtext.landin2.configurator.exco.Model#getConfigurator()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Configurator();

  /**
   * Returns the meta object for class '{@link itu.xtext.landin2.configurator.exco.Configurator <em>Configurator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Configurator</em>'.
   * @see itu.xtext.landin2.configurator.exco.Configurator
   * @generated
   */
  EClass getConfigurator();

  /**
   * Returns the meta object for the containment reference '{@link itu.xtext.landin2.configurator.exco.Configurator#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Title</em>'.
   * @see itu.xtext.landin2.configurator.exco.Configurator#getTitle()
   * @see #getConfigurator()
   * @generated
   */
  EReference getConfigurator_Title();

  /**
   * Returns the meta object for the containment reference list '{@link itu.xtext.landin2.configurator.exco.Configurator#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expression</em>'.
   * @see itu.xtext.landin2.configurator.exco.Configurator#getExpression()
   * @see #getConfigurator()
   * @generated
   */
  EReference getConfigurator_Expression();

  /**
   * Returns the meta object for class '{@link itu.xtext.landin2.configurator.exco.Title <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Title</em>'.
   * @see itu.xtext.landin2.configurator.exco.Title
   * @generated
   */
  EClass getTitle();

  /**
   * Returns the meta object for the attribute '{@link itu.xtext.landin2.configurator.exco.Title#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see itu.xtext.landin2.configurator.exco.Title#getName()
   * @see #getTitle()
   * @generated
   */
  EAttribute getTitle_Name();

  /**
   * Returns the meta object for class '{@link itu.xtext.landin2.configurator.exco.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see itu.xtext.landin2.configurator.exco.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the containment reference '{@link itu.xtext.landin2.configurator.exco.Expression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see itu.xtext.landin2.configurator.exco.Expression#getLeft()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Left();

  /**
   * Returns the meta object for the attribute list '{@link itu.xtext.landin2.configurator.exco.Expression#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Operation</em>'.
   * @see itu.xtext.landin2.configurator.exco.Expression#getOperation()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Operation();

  /**
   * Returns the meta object for the containment reference list '{@link itu.xtext.landin2.configurator.exco.Expression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see itu.xtext.landin2.configurator.exco.Expression#getRight()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Right();

  /**
   * Returns the meta object for the containment reference '{@link itu.xtext.landin2.configurator.exco.Expression#getParanthesis <em>Paranthesis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Paranthesis</em>'.
   * @see itu.xtext.landin2.configurator.exco.Expression#getParanthesis()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Paranthesis();

  /**
   * Returns the meta object for the attribute '{@link itu.xtext.landin2.configurator.exco.Expression#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see itu.xtext.landin2.configurator.exco.Expression#getName()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Name();

  /**
   * Returns the meta object for class '{@link itu.xtext.landin2.configurator.exco.FreeText <em>Free Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Free Text</em>'.
   * @see itu.xtext.landin2.configurator.exco.FreeText
   * @generated
   */
  EClass getFreeText();

  /**
   * Returns the meta object for the attribute '{@link itu.xtext.landin2.configurator.exco.FreeText#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see itu.xtext.landin2.configurator.exco.FreeText#getName()
   * @see #getFreeText()
   * @generated
   */
  EAttribute getFreeText_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ExcoFactory getExcoFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link itu.xtext.landin2.configurator.exco.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see itu.xtext.landin2.configurator.exco.impl.ModelImpl
     * @see itu.xtext.landin2.configurator.exco.impl.ExcoPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Configurator</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CONFIGURATOR = eINSTANCE.getModel_Configurator();

    /**
     * The meta object literal for the '{@link itu.xtext.landin2.configurator.exco.impl.ConfiguratorImpl <em>Configurator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see itu.xtext.landin2.configurator.exco.impl.ConfiguratorImpl
     * @see itu.xtext.landin2.configurator.exco.impl.ExcoPackageImpl#getConfigurator()
     * @generated
     */
    EClass CONFIGURATOR = eINSTANCE.getConfigurator();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIGURATOR__TITLE = eINSTANCE.getConfigurator_Title();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIGURATOR__EXPRESSION = eINSTANCE.getConfigurator_Expression();

    /**
     * The meta object literal for the '{@link itu.xtext.landin2.configurator.exco.impl.TitleImpl <em>Title</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see itu.xtext.landin2.configurator.exco.impl.TitleImpl
     * @see itu.xtext.landin2.configurator.exco.impl.ExcoPackageImpl#getTitle()
     * @generated
     */
    EClass TITLE = eINSTANCE.getTitle();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TITLE__NAME = eINSTANCE.getTitle_Name();

    /**
     * The meta object literal for the '{@link itu.xtext.landin2.configurator.exco.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see itu.xtext.landin2.configurator.exco.impl.ExpressionImpl
     * @see itu.xtext.landin2.configurator.exco.impl.ExcoPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__LEFT = eINSTANCE.getExpression_Left();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__OPERATION = eINSTANCE.getExpression_Operation();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__RIGHT = eINSTANCE.getExpression_Right();

    /**
     * The meta object literal for the '<em><b>Paranthesis</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__PARANTHESIS = eINSTANCE.getExpression_Paranthesis();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__NAME = eINSTANCE.getExpression_Name();

    /**
     * The meta object literal for the '{@link itu.xtext.landin2.configurator.exco.impl.FreeTextImpl <em>Free Text</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see itu.xtext.landin2.configurator.exco.impl.FreeTextImpl
     * @see itu.xtext.landin2.configurator.exco.impl.ExcoPackageImpl#getFreeText()
     * @generated
     */
    EClass FREE_TEXT = eINSTANCE.getFreeText();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FREE_TEXT__NAME = eINSTANCE.getFreeText_Name();

  }

} //ExcoPackage
