/**
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin2.configurator.exco;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link itu.xtext.landin2.configurator.exco.Model#getConfigurator <em>Configurator</em>}</li>
 * </ul>
 *
 * @see itu.xtext.landin2.configurator.exco.ExcoPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Configurator</b></em>' containment reference list.
   * The list contents are of type {@link itu.xtext.landin2.configurator.exco.Configurator}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Configurator</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Configurator</em>' containment reference list.
   * @see itu.xtext.landin2.configurator.exco.ExcoPackage#getModel_Configurator()
   * @model containment="true"
   * @generated
   */
  EList<Configurator> getConfigurator();

} // Model
