/*
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin2.configurator.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractExcoScopeProvider extends DelegatingScopeProvider {
}
